/**
 * Pinned native Hermes state.db compatibility.
 *
 * The checked-in store was generated by SessionDB at
 * NousResearch/hermes-agent@46d7718a52ff33accb15dc0501736fbdb6833cab with
 * redacted synthetic text. Set HERMES_API_CHECKOUT in the native CI lane to
 * regenerate it through that same pinned API for this run.
 */
import { afterEach, describe, expect, test } from 'bun:test';
import { Database } from 'bun:sqlite';
import { copyFileSync, existsSync, mkdtempSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { hermesAdapter, HERMES_SPEC_TARGET } from '../src/core/transcripts/hermes.ts';
import { trimSessionMessages } from '../src/core/transcripts/session-selection.ts';
import type { FileDiagnostics, ParsedSession } from '../src/core/transcripts/types.ts';

const checkedInFixture = join(import.meta.dir, 'fixtures/transcripts/hermes-native-state.db');
const tempDirs: string[] = [];
afterEach(() => { for (const dir of tempDirs.splice(0)) rmSync(dir, { recursive: true, force: true }); });

async function drain(path: string, sessionSources?: string[]) {
  const gen = hermesAdapter.parse(path, sessionSources ? { sessionSources } : undefined);
  const sessions: ParsedSession[] = [];
  let step = await gen.next();
  while (!step.done) { sessions.push(step.value); step = await gen.next(); }
  return { sessions, diagnostics: step.value as FileDiagnostics };
}

test('the verified schema contract is scoped to the exercised native Hermes pin', async () => {
  const parsed = await drain(nativeFixture());
  expect(parsed.sessions).toHaveLength(2);
  expect(HERMES_SPEC_TARGET.status).toBe('verified');
  expect(HERMES_SPEC_TARGET.references.join('\n')).toContain('46d7718a52ff33accb15dc0501736fbdb6833cab');
  expect(HERMES_SPEC_TARGET.note).toContain('Other revisions and populated production stores are not covered');
});

function nativeFixture(): string {
  const dir = mkdtempSync(join(tmpdir(), 'hermes-native-fixture-'));
  tempDirs.push(dir);
  const path = join(dir, 'state.db');
  const checkout = process.env.HERMES_API_CHECKOUT;
  const python = process.env.HERMES_FIXTURE_PYTHON;
  const requirePinned = process.env.HERMES_REQUIRE_PINNED_FIXTURE === '1';
  if (Boolean(checkout) !== Boolean(python)) {
    throw new Error('HERMES_API_CHECKOUT and HERMES_FIXTURE_PYTHON must be set together');
  }
  if (!checkout || !python) {
    if (requirePinned) throw new Error('Pinned Hermes fixture required; set HERMES_API_CHECKOUT and HERMES_FIXTURE_PYTHON');
    copyFileSync(checkedInFixture, path);
    return path;
  }
  const build = spawnSync(python, [join(import.meta.dir, 'hermes-python/build_state_fixture.py'), path], {
    encoding: 'utf8',
    env: process.env,
  });
  if (build.status !== 0) throw new Error(`Pinned Hermes fixture generation failed: ${build.stderr || build.stdout}`);
  return path;
}

describe('native Hermes state.db transcript compatibility', () => {
  test('keeps source selection exact and full archive semantics independent of live flags', async () => {
    const path = nativeFixture();
    const all = await drain(path);
    expect(all.diagnostics.sessions).toBe(2);
    expect(all.sessions.map(session => session.meta.sessionId)).toEqual(['fixture-cli', 'fixture-gateway']);
    const cli = all.sessions[0];
    expect(cli.meta.raw?.source).toBe('cli');
    expect(cli.messages.map(message => message.text)).toEqual([
      'SYNTHETIC-CUTOFF-USER', 'SYNTHETIC-ARCHIVE-ANSWER',
      'SYNTHETIC-REWOUND-TURN', 'SYNTHETIC-COMPACTED-TURN',
    ]);
    const selected = await drain(path, ['cli']);
    expect(selected.sessions.map(session => session.meta.sessionId)).toEqual(['fixture-cli']);
    expect(selected.sessions[0].meta.raw?.source).toBe('cli');
    const empty = await drain(path, ['cli%']);
    expect(empty.sessions).toHaveLength(0);
    expect(empty.diagnostics.expectedEmpty).toBe(true);

    const cutover = trimSessionMessages(cli, '2026-08-05T08:00:05.000Z');
    expect(cutover.messages.map(message => message.text)).toEqual([
      'SYNTHETIC-ARCHIVE-ANSWER', 'SYNTHETIC-REWOUND-TURN', 'SYNTHETIC-COMPACTED-TURN',
    ]);
    expect(cutover.meta.sessionId).not.toBe(cli.meta.sessionId);
    expect(cutover.meta.raw?.source_session_id).toBe('fixture-cli');
    expect(trimSessionMessages(cli, '2026-08-05T08:00:05Z').meta.sessionId).toBe(cutover.meta.sessionId);
    expect(cli.messages).toHaveLength(4); // trimming is a separate view, never destructive
  }, 30_000);

  test('reads a cleanly closed WAL-mode store when SQLite left no WAL sidecar', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'hermes-closed-wal-'));
    tempDirs.push(dir);
    const path = join(dir, 'state.db');
    copyFileSync(checkedInFixture, path);
    const writer = new Database(path);
    writer.exec('PRAGMA journal_mode=WAL;');
    writer.close();
    expect(existsSync(path + '-wal') ? statSync(path + '-wal').size : 0).toBe(0);
    const parsed = await drain(path, ['cli']);
    expect(parsed.sessions).toHaveLength(1);
    expect(parsed.sessions[0].messages.map(message => message.text)).toContain('SYNTHETIC-ARCHIVE-ANSWER');
  });

  test('snapshots committed live-WAL messages coherently without mutating the source store', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'hermes-live-wal-'));
    tempDirs.push(dir);
    const path = join(dir, 'state.db');
    copyFileSync(checkedInFixture, path);
    const writer = new Database(path);
    try {
      writer.exec('PRAGMA journal_mode=WAL; PRAGMA wal_autocheckpoint=0;');
      writer.query("INSERT INTO messages(session_id, role, content, timestamp) VALUES ('fixture-cli','assistant','SYNTHETIC-LIVE-WAL-MARKER',1785916830)").run();
      expect(writer.query('PRAGMA wal_checkpoint(PASSIVE)').get()).toBeDefined();
      // Ensure the test actually exercises an uncheckpointed live WAL frame.
      writer.query("INSERT INTO messages(session_id, role, content, timestamp) VALUES ('fixture-cli','user','SYNTHETIC-UNCKPT-WAL-MARKER',1785916835)").run();
      expect(existsSync(path + '-wal') && statSync(path + '-wal').size).toBeGreaterThan(0);
      const before = writer.query("SELECT content FROM messages WHERE content LIKE 'SYNTHETIC-%' ORDER BY id").all();
      const parsed = await drain(path, ['cli']);
      expect(parsed.sessions).toHaveLength(1);
      expect(parsed.sessions[0].messages.map(message => message.text)).toContain('SYNTHETIC-UNCKPT-WAL-MARKER');
      expect(writer.query("SELECT content FROM messages WHERE content LIKE 'SYNTHETIC-%' ORDER BY id").all()).toEqual(before);
    } finally {
      writer.close();
    }
  });
});
