#!/usr/bin/env python3
"""gen:contracts — generate Python contracts from spec files.
Source of truth: *.spec.md. Never edit the generated contracts directly.
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
_CONTRACTS_DIR = Path(__file__).parent.parent / "contracts"

_HEADER = '''"""
AUTO-GENERATED by gen:contracts. DO NOT EDIT.
Source of truth: openspec/changes/*/specs/{domain}/{action}.spec.md
"""
from __future__ import annotations
from typing import TypedDict, List


'''

_LOAD_CONTRACT = '''class SkillLoadInput(TypedDict):
    query: str  # required, non-empty


class SkillLoadSuccess(TypedDict):
    matched: int   # >= 0
    content: str   # concatenated skill bodies; empty string when matched=0


class SkillLoadError(TypedDict):
    code: str    # EMPTY_QUERY | SKILLS_DIR_MISSING
    message: str


def validate_skill_load_input(data: dict) -> SkillLoadInput:
    """Raise ValueError with reason if input is invalid."""
    if not isinstance(data, dict):
        raise ValueError("input must be a dict")
    query = data.get("query")
    if query is None:
        raise ValueError("missing required field: query")
    if not isinstance(query, str):
        raise ValueError("query must be a string")
    if not query.strip():
        raise ValueError("query must not be empty (EMPTY_QUERY)")
    return SkillLoadInput(query=query)


def build_skill_load_success(matched: int, content: str) -> SkillLoadSuccess:
    assert isinstance(matched, int) and matched >= 0
    assert isinstance(content, str)
    return SkillLoadSuccess(matched=matched, content=content)


def build_skill_load_error(code: str, message: str) -> SkillLoadError:
    assert code in ("EMPTY_QUERY", "SKILLS_DIR_MISSING")
    return SkillLoadError(code=code, message=message)
'''

_LIST_CONTRACT = '''class SkillEntry(TypedDict):
    name: str
    keywords: List[str]


class SkillListSuccess(TypedDict):
    count: int
    skills: List[SkillEntry]


class SkillListError(TypedDict):
    code: str    # SKILLS_DIR_MISSING
    message: str


_ALLOWED_SKILL_LIST_KEYS: frozenset = frozenset()


def validate_skill_list_input(data: dict) -> dict:
    """skill_list accepts only an empty dict; unknown fields are rejected."""
    if not isinstance(data, dict):
        raise ValueError("input must be a dict")
    unknown = set(data.keys()) - _ALLOWED_SKILL_LIST_KEYS
    if unknown:
        raise ValueError(f"unexpected fields: {sorted(unknown)}")
    return {}


def build_skill_list_success(skills: list) -> SkillListSuccess:
    entries = [SkillEntry(name=s["name"], keywords=list(s["keywords"])) for s in skills]
    return SkillListSuccess(count=len(entries), skills=entries)


def build_skill_list_error(code: str, message: str) -> SkillListError:
    assert code in ("SKILLS_DIR_MISSING",)
    return SkillListError(code=code, message=message)
'''


_INBOX_CHECK_CONTRACT = '''class InboxTask(TypedDict):
    slug: str
    title: str
    assigned_to: str
    created_by: str
    created: str
    task_excerpt: str


class InboxCheckSuccess(TypedDict):
    found: int           # >= 0
    tasks: List[InboxTask]


class InboxCheckError(TypedDict):
    code: str    # SEARCH_FAILED | INVALID_LIMIT
    message: str


def validate_inbox_check_input(data: dict) -> dict:
    """Raise ValueError if input is invalid."""
    if not isinstance(data, dict):
        raise ValueError("input must be a dict")
    result: dict = {}
    if "assigned_to" in data:
        v = data["assigned_to"]
        if not isinstance(v, str) or not v.strip():
            raise ValueError("assigned_to must be a non-empty string")
        result["assigned_to"] = v
    else:
        result["assigned_to"] = "local-ai"
    if "limit" in data:
        v = data["limit"]
        if not isinstance(v, int) or isinstance(v, bool):
            raise ValueError("limit must be an integer")
        if v <= 0:
            raise ValueError("limit must be > 0 (INVALID_LIMIT)")
        if v > 20:
            raise ValueError("limit must be <= 20 (INVALID_LIMIT)")
        result["limit"] = v
    else:
        result["limit"] = 5
    return result


def build_inbox_check_success(tasks: list) -> InboxCheckSuccess:
    entries = [
        InboxTask(
            slug=t["slug"],
            title=t["title"],
            assigned_to=t["assigned_to"],
            created_by=t["created_by"],
            created=t["created"],
            task_excerpt=t["task_excerpt"],
        )
        for t in tasks
    ]
    return InboxCheckSuccess(found=len(entries), tasks=entries)


def build_inbox_check_error(code: str, message: str) -> InboxCheckError:
    assert code in ("SEARCH_FAILED", "INVALID_LIMIT")
    return InboxCheckError(code=code, message=message)
'''


def main():
    _CONTRACTS_DIR.mkdir(parents=True, exist_ok=True)

    out_load  = _CONTRACTS_DIR / "skills_load_contract.py"
    out_list  = _CONTRACTS_DIR / "skills_list_contract.py"
    out_inbox = _CONTRACTS_DIR / "inbox_check_contract.py"

    out_load.write_text(_HEADER + _LOAD_CONTRACT)
    out_list.write_text(_HEADER + _LIST_CONTRACT)
    out_inbox.write_text(_HEADER + _INBOX_CHECK_CONTRACT)

    base = Path(__file__).parent.parent.parent
    print(f"✓ generated {out_load.relative_to(base)}")
    print(f"✓ generated {out_list.relative_to(base)}")
    print(f"✓ generated {out_inbox.relative_to(base)}")


if __name__ == "__main__":
    main()
