export type RequiredParityEngine = 'sqlite' | 'pglite';

export interface RequiredParityMatrixEntry {
  id: 'page-crud' | 'tags-links-timeline' | 'derived-jobs' | 'slug-rename' | 'memory-governance-lifecycle' | 'personal-memory' | 'note-structure';
  engines: readonly RequiredParityEngine[];
  required_operations: readonly string[];
  assertions: readonly string[];
}

const SQLITE_PGLITE = ['sqlite', 'pglite'] as const;

export const REQUIRED_PARITY_MATRIX: readonly RequiredParityMatrixEntry[] = [
  {
    id: 'page-crud',
    engines: SQLITE_PGLITE,
    required_operations: ['putPage', 'getPage', 'listPages', 'deletePage'],
    assertions: [
      'round-trip preserves page fields',
      'missing page returns null',
      'delete removes page and indexes',
    ],
  },
  {
    id: 'tags-links-timeline',
    engines: SQLITE_PGLITE,
    required_operations: ['addTag', 'getTags', 'addLink', 'getLinksForSlugs', 'getBacklinksForSlugs', 'addTimelineEntry', 'getTimeline'],
    assertions: [
      'tag filters match across engines',
      'forward and reverse links match across engines',
      'same-date timeline ordering matches across engines',
    ],
  },
  {
    id: 'derived-jobs',
    engines: SQLITE_PGLITE,
    required_operations: ['enqueueDerivedJob', 'listDerivedJobs', 'getDerivedIndexState'],
    assertions: [
      'derived job identity and status fields round-trip',
      'derived job list ordering is stable',
      'pending derived index state matches the queued job',
    ],
  },
  {
    id: 'memory-governance-lifecycle',
    engines: SQLITE_PGLITE,
    required_operations: [
      'createMemoryCandidateEntry',
      'getMemoryCandidateEntry',
      'listMemoryCandidateEntries',
      'createMemoryCandidateStatusEvent',
      'listMemoryCandidateStatusEvents',
      'updateMemoryCandidateEntryStatus',
      'updateMemoryCandidateEntryVerification',
      'promoteMemoryCandidateEntry',
      'createCanonicalHandoffEntry',
      'completeCanonicalHandoffEntry',
      'getCanonicalHandoffEntry',
      'listCanonicalHandoffEntries',
    ],
    assertions: [
      'candidate lifecycle fields round-trip identically across engines',
      'status events preserve kind and transition order across engines',
      'canonical handoff completion fields match across engines',
    ],
  },
  {
    id: 'personal-memory',
    engines: SQLITE_PGLITE,
    required_operations: [
      'upsertProfileMemoryEntry',
      'getProfileMemoryEntry',
      'listProfileMemoryEntries',
      'deleteProfileMemoryEntry',
      'createPersonalEpisodeEntry',
      'getPersonalEpisodeEntry',
      'listPersonalEpisodeEntries',
      'deletePersonalEpisodeEntry',
    ],
    assertions: [
      'profile memory upsert/list/delete round-trips identically across engines',
      'personal episode create/list/delete round-trips identically across engines',
    ],
  },
  {
    id: 'note-structure',
    engines: SQLITE_PGLITE,
    required_operations: [
      'upsertNoteManifestEntry',
      'getNoteManifestEntry',
      'listNoteManifestEntries',
      'deleteNoteManifestEntry',
      'replaceNoteSectionEntries',
      'getNoteSectionEntry',
      'listNoteSectionEntries',
      'deleteNoteSectionEntries',
    ],
    assertions: [
      'note manifest structural fields round-trip identically across engines',
      'note section replacement and lookup match across engines',
    ],
  },
  {
    id: 'slug-rename',
    engines: SQLITE_PGLITE,
    required_operations: ['renamePageSlug', 'getPage', 'getLinksForSlugs', 'getBacklinksForSlugs'],
    assertions: [
      'page slug moves without losing content',
      'links and backlinks point at the renamed slug',
    ],
  },
];

/**
 * Shared engine methods (implemented by both SQLiteEngine and PgEngineBase)
 * that are NOT yet covered by a REQUIRED_PARITY_MATRIX entry.
 *
 * Ratchet contract, enforced by test/parity-matrix.test.ts:
 * - A NEW shared engine method must either join a matrix entry's
 *   required_operations (with a behavioral parity seed) or be consciously
 *   added here — it can never be silently uncovered.
 * - Entries may only be REMOVED from this list (by gaining parity coverage);
 *   stale or duplicate entries fail the test.
 */
export const PARITY_COVERAGE_BACKLOG: readonly string[] = [
  'attachMemoryRealmToSession',
  'bindMemoryCandidateTarget',
  'claimNextDerivedJob',
  'claimNextDerivedJobInTransaction',
  'closeMemorySession',
  'consumeMemoryWriteSession',
  'countMemoryCandidateEntries',
  'createCanonicalTargetProposalEntry',
  'createCanonicalTargetProposalStatusEvent',
  'createContextEvalCorrection',
  'createMemoryCandidateContradictionEntry',
  'createMemoryMutationEvent',
  'createMemoryRedactionPlan',
  'createMemoryRedactionPlanItem',
  'createMemorySession',
  'createMemoryWriteSession',
  'createTaskThread',
  'createVersion',
  'deleteChunks',
  'deleteContextAtlasEntry',
  'deleteContextMapEntry',
  'deleteMemoryCandidateEntry',
  'enqueueDerivedJobInTransaction',
  'getAutoPromoteVerdict',
  'getBacklinks',
  'getCanonicalTargetProposalEntry',
  'getChunks',
  'getChunksWithEmbeddings',
  'getConfig',
  'getContextAtlasEntry',
  'getContextEvalRun',
  'getContextMapEntry',
  'getDerivedJobById',
  'getHealth',
  'getIngestLog',
  'getLinks',
  'getMemoryCandidateContradictionEntry',
  'getMemoryCandidateSupersessionEntry',
  'getMemoryRealm',
  'getMemoryRedactionPlan',
  'getMemorySession',
  'getMemoryWriteSession',
  'getPageEmbeddings',
  'getPageForUpdate',
  'getPageLineSpanProjection',
  'getPageProjection',
  'getRawData',
  'getRetrievalTrace',
  'getStats',
  'getTaskThread',
  'getTaskWorkingSet',
  'getVersions',
  'getWatchedQuestion',
  'listCanonicalHandoffEntriesByInteractionIds',
  'listCanonicalTargetProposalEntries',
  'listCanonicalTargetProposalStatusEvents',
  'listContextAtlasEntries',
  'listContextEvalAssertions',
  'listContextEvalRuns',
  'listContextMapEntries',
  'listDerivedIndexStates',
  'listMemoryCandidateContradictionEntriesByInteractionIds',
  'listMemoryCandidateContradictionEntriesForCandidateIds',
  'listMemoryCandidateStatusEventsByInteractionIds',
  'listMemoryCandidateSupersessionEntriesByInteractionIds',
  'listMemoryMutationEvents',
  'listMemoryRealms',
  'listMemoryRedactionPlanItems',
  'listMemoryRedactionPlans',
  'listMemorySessionAttachments',
  'listMemorySessions',
  'listMemoryWriteSessions',
  'listRetrievalTraces',
  'listRetrievalTracesByWindow',
  'listTaskAttempts',
  'listTaskDecisions',
  'listTaskThreads',
  'listWatchedQuestionRuns',
  'listWatchedQuestions',
  'logIngest',
  'markDerivedIndexReady',
  'markDerivedIndexReadyInTransaction',
  'markDerivedJobFailed',
  'markDerivedJobFailedInTransaction',
  'memoryCandidateFilterWhereClause',
  'putAutoPromoteVerdict',
  'putContextEvalAssertion',
  'putContextEvalRun',
  'putRawData',
  'putRetrievalTrace',
  'readSchemaVersionForHealth',
  'recordTaskAttempt',
  'recordTaskDecision',
  'recordWatchedQuestionRun',
  'refreshPageSearchText',
  'releaseDerivedJobLease',
  'releaseDerivedJobLeaseInTransaction',
  'removeLink',
  'removeTag',
  'resolveSlugs',
  'revertToVersion',
  'rewriteLinks',
  'searchKeyword',
  'searchVector',
  'setConfig',
  'setWatchedQuestionEnabled',
  'supersedeMemoryCandidateEntry',
  'traverseGraph',
  'updateCanonicalTargetProposalDraft',
  'updateCanonicalTargetProposalStatus',
  'updateMemoryCandidatePatchOperationState',
  'updateMemoryRedactionPlanItemStatus',
  'updateMemoryRedactionPlanStatus',
  'updatePageEmbedding',
  'updateSlug',
  'updateTaskThread',
  'updateWatchedQuestionSnapshot',
  'upsertChunks',
  'upsertContextAtlasEntry',
  'upsertContextMapEntry',
  'upsertFailedDerivedIndexStateFromJob',
  'upsertMemoryRealm',
  'upsertPendingDerivedIndexState',
  'upsertPendingDerivedIndexStateFromJob',
  'upsertTaskWorkingSet',
  'upsertWatchedQuestion',
];
