"""
AUTO-GENERATED by gen:contracts. DO NOT EDIT.
Source of truth: openspec/changes/*/specs/{domain}/{action}.spec.md
"""
from __future__ import annotations
from typing import TypedDict, List


class InboxTask(TypedDict):
    slug: str
    title: str
    assigned_to: str
    created_by: str
    created: str
    task_excerpt: str


class InboxCheckSuccess(TypedDict):
    found: int           # >= 0
    tasks: List[InboxTask]


class InboxCheckError(TypedDict):
    code: str    # SEARCH_FAILED | INVALID_LIMIT
    message: str


def validate_inbox_check_input(data: dict) -> dict:
    """Raise ValueError if input is invalid."""
    if not isinstance(data, dict):
        raise ValueError("input must be a dict")
    result: dict = {}
    if "assigned_to" in data:
        v = data["assigned_to"]
        if not isinstance(v, str) or not v.strip():
            raise ValueError("assigned_to must be a non-empty string")
        result["assigned_to"] = v
    else:
        result["assigned_to"] = "local-ai"
    if "limit" in data:
        v = data["limit"]
        if not isinstance(v, int) or isinstance(v, bool):
            raise ValueError("limit must be an integer")
        if v <= 0:
            raise ValueError("limit must be > 0 (INVALID_LIMIT)")
        if v > 20:
            raise ValueError("limit must be <= 20 (INVALID_LIMIT)")
        result["limit"] = v
    else:
        result["limit"] = 5
    return result


def build_inbox_check_success(tasks: list) -> InboxCheckSuccess:
    entries = [
        InboxTask(
            slug=t["slug"],
            title=t["title"],
            assigned_to=t["assigned_to"],
            created_by=t["created_by"],
            created=t["created"],
            task_excerpt=t["task_excerpt"],
        )
        for t in tasks
    ]
    return InboxCheckSuccess(found=len(entries), tasks=entries)


def build_inbox_check_error(code: str, message: str) -> InboxCheckError:
    assert code in ("SEARCH_FAILED", "INVALID_LIMIT")
    return InboxCheckError(code=code, message=message)
