"""
AUTO-GENERATED by gen:contracts. DO NOT EDIT.
Source of truth: openspec/changes/*/specs/{domain}/{action}.spec.md
"""
from __future__ import annotations
from typing import TypedDict, List


class SkillEntry(TypedDict):
    name: str
    keywords: List[str]


class SkillListSuccess(TypedDict):
    count: int
    skills: List[SkillEntry]


class SkillListError(TypedDict):
    code: str    # SKILLS_DIR_MISSING
    message: str


_ALLOWED_SKILL_LIST_KEYS: frozenset = frozenset()


def validate_skill_list_input(data: dict) -> dict:
    """skill_list accepts only an empty dict; unknown fields are rejected."""
    if not isinstance(data, dict):
        raise ValueError("input must be a dict")
    unknown = set(data.keys()) - _ALLOWED_SKILL_LIST_KEYS
    if unknown:
        raise ValueError(f"unexpected fields: {sorted(unknown)}")
    return {}


def build_skill_list_success(skills: list) -> SkillListSuccess:
    entries = [SkillEntry(name=s["name"], keywords=list(s["keywords"])) for s in skills]
    return SkillListSuccess(count=len(entries), skills=entries)


def build_skill_list_error(code: str, message: str) -> SkillListError:
    assert code in ("SKILLS_DIR_MISSING",)
    return SkillListError(code=code, message=message)
