"""
AUTO-GENERATED by gen:contracts. DO NOT EDIT.
Source of truth: openspec/changes/*/specs/{domain}/{action}.spec.md
"""
from __future__ import annotations
from typing import TypedDict, List


class SkillLoadInput(TypedDict):
    query: str  # required, non-empty


class SkillLoadSuccess(TypedDict):
    matched: int   # >= 0
    content: str   # concatenated skill bodies; empty string when matched=0


class SkillLoadError(TypedDict):
    code: str    # EMPTY_QUERY | SKILLS_DIR_MISSING
    message: str


def validate_skill_load_input(data: dict) -> SkillLoadInput:
    """Raise ValueError with reason if input is invalid."""
    if not isinstance(data, dict):
        raise ValueError("input must be a dict")
    query = data.get("query")
    if query is None:
        raise ValueError("missing required field: query")
    if not isinstance(query, str):
        raise ValueError("query must be a string")
    if not query.strip():
        raise ValueError("query must not be empty (EMPTY_QUERY)")
    return SkillLoadInput(query=query)


def build_skill_load_success(matched: int, content: str) -> SkillLoadSuccess:
    assert isinstance(matched, int) and matched >= 0
    assert isinstance(content, str)
    return SkillLoadSuccess(matched=matched, content=content)


def build_skill_load_error(code: str, message: str) -> SkillLoadError:
    assert code in ("EMPTY_QUERY", "SKILLS_DIR_MISSING")
    return SkillLoadError(code=code, message=message)
