#!/usr/bin/env python3
"""Apply rendered soul-audit identity files to a Hermes Agent home.

Hermes Agent loads its persona from SOUL.md in its own home ($HERMES_HOME,
default ~/.hermes; each profile is its own home). It reads nothing from a
bootstrap workspace. This helper composes the five files `gbrain bootstrap
render` wrote into the bank workspace into ONE managed block in
<hermes-home>/SOUL.md:

  - all five rendered files must be present; nothing is written otherwise;
  - the block sits between BEGIN/END markers; a re-run replaces only the
    block, and every byte outside it is kept as it was;
  - a SOUL.md with the user's own text and no block is never changed until
    the user picks --mode append or --mode replace (exit 3 = ask the user);
  - every write backs the previous file up under <hermes-home>/backups/;
  - a symlinked SOUL.md is refused unless --follow-symlink is given.

The block's text is copied from the rendered files. Sections are selected by
their `## ` headings (render escapes line-leading `#` in answers, so an answer
can never forge one). The only edits are TEMPLATE_DROPS and TEMPLATE_EDITS:
fixed template sentences that only make sense in a bootstrap workspace. Each
is applied only when it matches exactly once, so answer text is never removed
or rewritten; at worst a workspace-only sentence stays in. The helper adds two
sentences of its own, marked in HERMES_NOTES. Standard library; Python 3.8+.

Usage:
  python3 hermes_apply.py --workspace <bank workspace> [--hermes-home DIR]
                          [--mode append|replace] [--follow-symlink] [--dry-run]

Exit codes: 0 written, unchanged, or dry run shown; 1 error (nothing written);
2 usage; 3 SOUL.md holds the user's own text and no block: ask the user, then
re-run with --mode append or --mode replace.
"""

import argparse
import difflib
import os
import re
import shutil
import sys
import tempfile
import time
from typing import NoReturn

BEGIN = "<!-- gbrain:soul-audit:begin -->"
END = "<!-- gbrain:soul-audit:end -->"
MARKER_STEM = "<!-- gbrain:soul-audit:"
NOTE = (
    "<!-- Generated by the gbrain soul-audit skill from the interview bank. "
    "Change an answer and re-run the skill; edits between these markers are replaced. -->"
)
RENDERED = ("SOUL.md", "USER.md", "AGENTS.md", "ACCESS_POLICY.md", "HEARTBEAT.md")
RENDER_HINT = "--only " + ",".join(RENDERED) + " --force"
# Hermes truncates context files above context_file_max_chars; 20,000 is its floor.
HERMES_CONTEXT_FLOOR = 20000
EXIT_NEEDS_USER = 3
P = "\x00PRINCIPAL\x00"  # stands for an interpolated {{PRINCIPAL_NAME}} in the patterns below

# Template-owned text that only applies to a bootstrap workspace. Each entry is
# the exact template wording; it is removed only when it matches exactly once.
TEMPLATE_DROPS = (
    # The bootstrap workspace repo is not Hermes's home.
    "\n\n\u26d4 **PRIVATE REPO PERSISTENCE.** This workspace is the durable self: identity,\n"
    "memory, brain, skills, schedules. After meaningful changes, ensure it reaches the\n"
    "private remote (`gbrain sources push` does this with a secret scan; it refuses\n"
    "public remotes). Never let valuable work exist only on one machine. If something\n"
    "seems broken, the one command to run is `gbrain doctor`.",
    # Hermes routes its own skills.
    "\n\n**Gate 6 \u2014 Skill routing.** If the request matches a skill in `skills/`, read that\n"
    "SKILL.md and follow it. Category match beats style preference. Never narrate routing\n"
    "\u2014 select and produce.",
    # The hooks / pull-protocol note is about Codex and opencode workspaces.
    " On a harness WITHOUT hooks (Codex / opencode \u2014 pull protocol), also run\n"
    "`gbrain bootstrap status` once at the start of a conversation: it surfaces a\n"
    "failing or stale workspace push that hook-carrying harnesses would have shown\n"
    "automatically. If it reports the push FAILING, tell " + P + " plainly \u2014\n"
    "their memory is landing locally but not in the durable repo.",
    # `gbrain bootstrap status` reports on a bootstrap workspace.
    " When " + P + " says something's\n"
    "broken, run `gbrain bootstrap status --json` and relay its `support` block\n"
    "verbatim \u2014 it carries the versions, registrations, and last-verify state a fixer\n"
    "needs; do not paraphrase it.",
)
TEMPLATE_EDITS = (
    ("`AGENTS.md` says what to do", "The Jobs section below says what to do"),
    ("the priority order in `AGENTS.md` wins", "the priority order in Jobs wins"),
    ("Gate 0 (AGENTS.md): ", "Gate 0: "),
    # SURFACE_PRIMARY's default; an answer of the user's own is left alone.
    ("**Primary surface:** this workspace (Claude Code / Codex / opencode)", "**Primary surface:** Hermes Agent"),
    (
        "- Operational state (open commitments, corrections, active context) \u2192 `MEMORY.md`\n"
        "  and `memory/YYYY-MM-DD.md` (file edits are correct for these two \u2014 they are loaded\n"
        "  by path, not by search).",
        "- Operational state (open commitments, corrections, active context) \u2192 Hermes memory,\n"
        "  through the `memory` tool; Hermes loads it every session.",
    ),
)
# The only sentences the helper writes itself.
HERMES_NOTES = {
    "access": "This is prompt-level policy. Who can reach this agent at all is set by the "
              "Hermes gateway allowlists and pairing, not by this text.",
    "cadence": "On Hermes, recurring work runs as Hermes cron jobs, created one at a time after "
               "the principal approves a manual run. This block creates none.",
}


def fail(message, code=1) -> NoReturn:
    sys.stderr.write("hermes_apply: " + message + "\n")
    sys.exit(code)


def read(path):
    try:
        with open(path, "rb") as handle:
            raw = handle.read()
    except OSError as exc:
        fail("cannot read %s: %s" % (path, exc))
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError:
        fail("%s is not UTF-8 text. Convert it to UTF-8 (or move it aside), then re-run. Nothing was written." % path)


def section(text, heading):
    """Body of the `## heading` section (without the heading line), or None."""
    lines = text.splitlines()
    for index, line in enumerate(lines):
        if line.strip() == "## " + heading:
            body = []
            for follow in lines[index + 1:]:
                if follow.startswith("## ") or follow.startswith("# "):
                    break
                body.append(follow)
            return "\n".join(body).strip()
    return None


def need(text, heading, name):
    body = section(text, heading)
    if body is None:
        fail("the rendered %s has no '## %s' section. It was not made by this gbrain's bootstrap "
             "render; render again with %s. Nothing was written." % (name, heading, RENDER_HINT))
    return body


def template_pattern(fixed):
    """Regex for exact template text; P matches one interpolated name (no paragraph break)."""
    return r"(?:(?!\n\n)[^\x00])+?".join(re.escape(part) for part in fixed.split(P))


def once(body, fixed, replacement):
    """Replace template text only when it occurs exactly once; otherwise leave the body alone."""
    if P not in fixed:
        return body.replace(fixed, replacement) if body.count(fixed) == 1 else body
    pattern = template_pattern(fixed)
    matches = list(re.finditer(pattern, body))
    if len(matches) != 1:
        return body
    return body[:matches[0].start()] + replacement + body[matches[0].end():]


def demote(text):
    """Turn `## X` headings into `### X` so a section nests under the block's own heading."""
    return re.sub(r"^(#{2,5}) ", lambda m: "#" + m.group(1) + " ", text, flags=re.M)


def compose(ws):
    """Build the managed block from the five rendered files in the bank workspace."""
    missing = [name for name in RENDERED if not os.path.isfile(os.path.join(ws, name))]
    if missing:
        fail("%s missing from %s. Render all five first: gbrain bootstrap render --workspace %s %s. "
             "Nothing was written." % (", ".join(missing), ws, ws, RENDER_HINT))
    soul, user, agents, access, heartbeat = (read(os.path.join(ws, name)) for name in RENDERED)

    user_lines = user.strip().splitlines()
    user_body = "\n".join(user_lines[1:] if user_lines and user_lines[0].startswith("# ") else user_lines)
    # The maintenance note is about the workspace file; the bank answers are the record here.
    user_body = re.sub(r"\n## Keeping this file true\n.*\Z", "", user_body.strip(), flags=re.S).strip()

    cadence_section = need(heartbeat, "Due-job list", "HEARTBEAT.md")
    cadence = re.split(r"\(machine-local,\s*\nnot committed\)\.", cadence_section, maxsplit=1)
    cadence_answer = cadence[1].strip() if len(cadence) == 2 else ""

    parts = [
        soul.strip(),
        "## Jobs\n\n" + need(agents, "Mission", "AGENTS.md"),
        "## Operating gates\n\n" + need(agents, "Hard gates", "AGENTS.md")
        + "\n\n" + need(agents, "Per-message gates", "AGENTS.md"),
        "## Who I serve\n\n" + demote(user_body),
        "## Access\n\n" + need(access, "Tiers", "ACCESS_POLICY.md")
        + "\n\nBoundaries that never move:\n\n" + need(access, "Boundaries that never move", "ACCESS_POLICY.md")
        + "\n\nWhat the model provider sees: " + need(access, "What the model provider sees", "ACCESS_POLICY.md")
        + "\n\n" + HERMES_NOTES["access"],
        "## Quiet hours and proactive output\n\n" + need(heartbeat, "Before anything", "HEARTBEAT.md")
        + "\n\n" + need(heartbeat, "The silence contract", "HEARTBEAT.md"),
    ]
    if cadence_answer:
        parts.append("## Check-in cadence\n\n" + cadence_answer + "\n\n" + HERMES_NOTES["cadence"])
    parts.append("## Filing contract (where knowledge goes)\n\n"
                 + need(agents, "Filing contract (where knowledge goes)", "AGENTS.md"))

    body = "\n\n".join(parts)
    for fixed in TEMPLATE_DROPS:
        body = once(body, fixed, "")
    for old, new in TEMPLATE_EDITS:
        body = once(body, old, new)
    # An answer that quotes a block marker must never become a delimiter.
    body = body.replace(MARKER_STEM, "&lt;!-- gbrain:soul-audit:")

    leftover = sorted(set(re.findall(r"\{\{([A-Z0-9_]+)\}\}", body)))
    if leftover:
        fail("the rendered files still contain unanswered placeholders (%s). Ask the user for those "
             "answers, confirm the read-back, and render again. Nothing was written." % ", ".join(leftover))
    block = "\n".join([BEGIN, NOTE, "", body, "", END])
    if block.count(BEGIN) != 1 or block.count(END) != 1:
        fail("internal error: the composed block does not have exactly one pair of markers. Nothing was written.")
    return block


def looks_like_stock_hermes_soul(text):
    stripped = text.strip()
    return stripped.startswith("You are Hermes Agent, built by Nous Research.") or (
        stripped.startswith("# Hermes Agent Persona") and len(stripped) < 1200
    )


def plan(existing, block, mode):
    """Return (new_text, action). Text outside the block is never altered. Exits 3 when the user must choose."""
    if existing is None:
        return block + "\n", "created"
    if not existing.strip():
        return block + "\n", "filled the empty file"
    newline = "\r\n" if existing.count("\r\n") * 2 > existing.count("\n") else "\n"
    block = block.replace("\n", newline)
    begins, ends = existing.count(BEGIN), existing.count(END)
    if begins or ends:
        start, stop = existing.find(BEGIN), existing.find(END)
        if begins != 1 or ends != 1 or stop < start:
            fail("SOUL.md has %d begin and %d end markers; expected one of each, in order. Fix the markers "
                 "by hand (keep one block), then re-run. Nothing was written." % (begins, ends))
        return existing[:start] + block + existing[stop + len(END):], "replaced the managed block"
    if mode == "append":
        joiner = newline if existing.endswith("\n") else newline * 2
        return existing + joiner + block + newline, "appended the managed block"
    if mode == "replace":
        return block + newline, "replaced the whole file"
    hint = (
        " It looks like the stock Hermes default persona, which --mode replace swaps for the interview's identity."
        if looks_like_stock_hermes_soul(existing)
        else " It holds the user's own text, which --mode append keeps above the block."
    )
    sys.stderr.write(
        "hermes_apply: SOUL.md has no gbrain block yet." + hint + "\n"
        "Ask the user which they want, preview it with --dry-run --mode append|replace, then re-run with "
        "that --mode. Nothing was written.\n"
    )
    sys.exit(EXIT_NEEDS_USER)


def backup(source, home):
    stamp = time.strftime("%Y%m%d-%H%M%S")
    folder = os.path.join(home, "backups", "soul-audit-" + stamp)
    suffix = 1
    while os.path.exists(folder):
        suffix += 1
        folder = os.path.join(home, "backups", "soul-audit-%s-%d" % (stamp, suffix))
    os.makedirs(folder)
    dest = os.path.join(folder, "SOUL.md")
    shutil.copy2(source, dest)
    return dest


def write_atomic(path, text):
    directory = os.path.dirname(path)
    fd, tmp = tempfile.mkstemp(prefix=".SOUL.md.", suffix=".soul-audit", dir=directory)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as handle:
            handle.write(text)
        if os.path.exists(path):
            shutil.copymode(path, tmp)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def main():
    parser = argparse.ArgumentParser(description="Apply rendered soul-audit files to Hermes Agent's SOUL.md.")
    parser.add_argument("--workspace", required=True, help="bank workspace that gbrain bootstrap rendered into")
    parser.add_argument("--hermes-home", help="Hermes home (default: $HERMES_HOME, else ~/.hermes)")
    parser.add_argument("--mode", choices=["append", "replace"], help="first run on a SOUL.md with the user's own text")
    parser.add_argument("--follow-symlink", action="store_true", help="write through a symlinked SOUL.md to its target")
    parser.add_argument("--dry-run", action="store_true", help="print the diff and write nothing")
    args = parser.parse_args()

    ws = os.path.abspath(os.path.expanduser(args.workspace))
    home = args.hermes_home or os.environ.get("HERMES_HOME") or os.path.join(os.path.expanduser("~"), ".hermes")
    home = os.path.abspath(os.path.expanduser(os.path.expandvars(home)))
    if not os.path.isdir(home):
        fail("Hermes home %s does not exist. Pass --hermes-home (the folder holding config.yaml)." % home)
    if os.path.realpath(ws) == os.path.realpath(home):
        fail("the bank workspace must not be the Hermes home itself; use a subfolder such as %s"
             % os.path.join(home, "gbrain-identity"))

    target = os.path.join(home, "SOUL.md")
    if os.path.islink(target):
        if not args.follow_symlink:
            fail("%s is a symlink to %s. Ask the user before writing through it, then re-run with "
                 "--follow-symlink. Nothing was written." % (target, os.path.realpath(target)))
        target = os.path.realpath(target)

    existing = read(target) if os.path.exists(target) else None
    new_text, action = plan(existing, compose(ws), args.mode)

    if existing == new_text:
        print("unchanged: %s already holds this block" % target)
        return 0
    if args.dry_run:
        diff = difflib.unified_diff((existing or "").splitlines(True), new_text.splitlines(True),
                                    fromfile=target, tofile=target + " (new)")
        sys.stdout.writelines(diff)
        print("\ndry run: would have %s in %s (%d chars). Nothing was written." % (action, target, len(new_text)))
        return 0

    saved = backup(target, home) if existing is not None else None
    write_atomic(target, new_text)
    print("%s: %s (%d chars) from the bank in %s" % (action, target, len(new_text), ws))
    if saved:
        print("backup: %s" % saved)
    if len(new_text) > HERMES_CONTEXT_FLOOR:
        print("warning: SOUL.md is over %d chars; Hermes may truncate it on smaller models "
              "(context_file_max_chars)." % HERMES_CONTEXT_FLOOR)
    print("takes effect in new Hermes sessions; a session that is already running keeps its prompt.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
