// AUTO-GENERATED by scripts/build-operation-manifest.ts — do not edit by hand.
// Regenerate: bun run build:operation-manifest
// Freshness pinned by test/operation-manifest.test.ts.
//
// Merge conflict here? Take either side wholesale, then re-run the command above.
//
// Operation name -> [loader of its defining module, export holding it].
// String-literal import()s so bun --compile embeds every module.

const load_admin = () => import('./ops/admin.ts') as Promise<Record<string, unknown>>;
const load_attribution = () => import('./ops/attribution.ts') as Promise<Record<string, unknown>>;
const load_brain_membership = () => import('./ops/brain-membership.ts') as Promise<Record<string, unknown>>;
const load_calibration = () => import('./ops/calibration.ts') as Promise<Record<string, unknown>>;
const load_chronicle = () => import('./ops/chronicle.ts') as Promise<Record<string, unknown>>;
const load_chunks = () => import('./ops/chunks.ts') as Promise<Record<string, unknown>>;
const load_code_intel = () => import('./ops/code-intel.ts') as Promise<Record<string, unknown>>;
const load_connectors = () => import('./ops/connectors.ts') as Promise<Record<string, unknown>>;
const load_embedding_migration = () => import('./ops/embedding-migration.ts') as Promise<Record<string, unknown>>;
const load_entity_identity = () => import('./ops/entity-identity.ts') as Promise<Record<string, unknown>>;
const load_extraction = () => import('./ops/extraction.ts') as Promise<Record<string, unknown>>;
const load_facts = () => import('./ops/facts.ts') as Promise<Record<string, unknown>>;
const load_feedback = () => import('./ops/feedback.ts') as Promise<Record<string, unknown>>;
const load_files = () => import('./ops/files.ts') as Promise<Record<string, unknown>>;
const load_image = () => import('./ops/image.ts') as Promise<Record<string, unknown>>;
const load_ingest_log = () => import('./ops/ingest-log.ts') as Promise<Record<string, unknown>>;
const load_insights = () => import('./ops/insights.ts') as Promise<Record<string, unknown>>;
const load_jobs = () => import('./ops/jobs.ts') as Promise<Record<string, unknown>>;
const load_links = () => import('./ops/links.ts') as Promise<Record<string, unknown>>;
const load_loops = () => import('./ops/loops.ts') as Promise<Record<string, unknown>>;
const load_notices = () => import('./ops/notices.ts') as Promise<Record<string, unknown>>;
const load_orphans = () => import('./ops/orphans.ts') as Promise<Record<string, unknown>>;
const load_page_batch = () => import('./ops/page-batch.ts') as Promise<Record<string, unknown>>;
const load_page_edit = () => import('./ops/page-edit.ts') as Promise<Record<string, unknown>>;
const load_pages = () => import('./ops/pages.ts') as Promise<Record<string, unknown>>;
const load_persistence = () => import('./ops/persistence.ts') as Promise<Record<string, unknown>>;
const load_purge = () => import('./ops/purge.ts') as Promise<Record<string, unknown>>;
const load_raw_data = () => import('./ops/raw-data.ts') as Promise<Record<string, unknown>>;
const load_request_tools = () => import('./ops/request-tools.ts') as Promise<Record<string, unknown>>;
const load_salience = () => import('./ops/salience.ts') as Promise<Record<string, unknown>>;
const load_schema_packs = () => import('./ops/schema-packs.ts') as Promise<Record<string, unknown>>;
const load_search = () => import('./ops/search.ts') as Promise<Record<string, unknown>>;
const load_skillopt = () => import('./ops/skillopt.ts') as Promise<Record<string, unknown>>;
const load_skills_catalog = () => import('./ops/skills-catalog.ts') as Promise<Record<string, unknown>>;
const load_sources = () => import('./ops/sources.ts') as Promise<Record<string, unknown>>;
const load_sync_status = () => import('./ops/sync-status.ts') as Promise<Record<string, unknown>>;
const load_tags = () => import('./ops/tags.ts') as Promise<Record<string, unknown>>;
const load_takes = () => import('./ops/takes.ts') as Promise<Record<string, unknown>>;
const load_timeline = () => import('./ops/timeline.ts') as Promise<Record<string, unknown>>;
const load_transcripts = () => import('./ops/transcripts.ts') as Promise<Record<string, unknown>>;
const load_trust = () => import('./ops/trust.ts') as Promise<Record<string, unknown>>;
const load_usage = () => import('./ops/usage.ts') as Promise<Record<string, unknown>>;
const load_verbs = () => import('./verbs.ts') as Promise<Record<string, unknown>>;

export const OPERATION_LOADERS: Record<string, readonly [() => Promise<Record<string, unknown>>, string]> = {
  "remember": [load_verbs, "verbOperations"],
  "entity": [load_verbs, "verbOperations"],
  "synthesize": [load_verbs, "verbOperations"],
  "forget": [load_verbs, "verbOperations"],
  "get_page": [load_pages, "pagesOperations"],
  "put_page": [load_pages, "pagesOperations"],
  "delete_page": [load_pages, "pagesOperations"],
  "list_pages": [load_pages, "pagesOperations"],
  "restore_page": [load_pages, "pagesOperations"],
  "purge_deleted_pages": [load_pages, "pagesOperations"],
  "capture": [load_pages, "pagesOperations"],
  "fetch": [load_pages, "pagesOperations"],
  "edit_page": [load_page_edit, "pageEditOperations"],
  "put_pages": [load_page_batch, "pageBatchOperations"],
  "get_write_request": [load_persistence, "persistenceOperations"],
  "list_write_requests": [load_persistence, "persistenceOperations"],
  "cancel_write_request": [load_persistence, "persistenceOperations"],
  "search": [load_search, "searchOperations"],
  "query": [load_search, "searchOperations"],
  "assemble_evidence": [load_search, "searchOperations"],
  "search_stats": [load_search, "searchOperations"],
  "search_modes": [load_search, "searchOperations"],
  "search_tune": [load_search, "searchOperations"],
  "cache_stats": [load_search, "searchOperations"],
  "rate_answer": [load_feedback, "feedbackOperations"],
  "search_by_image": [load_image, "imageOperations"],
  "add_tag": [load_tags, "tagsOperations"],
  "remove_tag": [load_tags, "tagsOperations"],
  "get_tags": [load_tags, "tagsOperations"],
  "add_link": [load_links, "linksOperations"],
  "remove_link": [load_links, "linksOperations"],
  "get_links": [load_links, "linksOperations"],
  "get_backlinks": [load_links, "linksOperations"],
  "list_link_sources": [load_links, "linksOperations"],
  "traverse_graph": [load_links, "linksOperations"],
  "wanted_pages": [load_links, "linksOperations"],
  "add_timeline_entry": [load_timeline, "timelineOperations"],
  "get_timeline": [load_timeline, "timelineOperations"],
  "get_stats": [load_admin, "adminOperations"],
  "get_health": [load_admin, "adminOperations"],
  "run_doctor": [load_admin, "adminOperations"],
  "get_versions": [load_admin, "adminOperations"],
  "revert_version": [load_admin, "adminOperations"],
  "get_brain_identity": [load_admin, "adminOperations"],
  "quarantine_list": [load_admin, "adminOperations"],
  "get_write_attribution": [load_attribution, "attributionOperations"],
  "confirm_memory": [load_trust, "trustOperations"],
  "list_skills": [load_skills_catalog, "skillsCatalogOperations"],
  "get_skill": [load_skills_catalog, "skillsCatalogOperations"],
  "list_brain_skillpack": [load_skills_catalog, "skillsCatalogOperations"],
  "advisor": [load_skills_catalog, "skillsCatalogOperations"],
  "get_status_snapshot": [load_skills_catalog, "skillsCatalogOperations"],
  "get_skill_asset": [load_skills_catalog, "skillsCatalogOperations"],
  "put_skill": [load_skills_catalog, "skillsCatalogOperations"],
  "delete_skill": [load_skills_catalog, "skillsCatalogOperations"],
  "set_skill_policy": [load_skills_catalog, "skillsCatalogOperations"],
  "get_skill_policy": [load_skills_catalog, "skillsCatalogOperations"],
  "get_skill_retention": [load_skills_catalog, "skillsCatalogOperations"],
  "prune_skill_revisions": [load_skills_catalog, "skillsCatalogOperations"],
  "retain_skill_revision": [load_skills_catalog, "skillsCatalogOperations"],
  "import_skill_proposal": [load_skills_catalog, "skillsCatalogOperations"],
  "join_brain": [load_brain_membership, "brainMembershipOperations"],
  "sync_brain_skills": [load_brain_membership, "brainMembershipOperations"],
  "leave_brain": [load_brain_membership, "brainMembershipOperations"],
  "sync_brain": [load_sync_status, "syncStatusOperations"],
  "put_raw_data": [load_raw_data, "rawDataOperations"],
  "get_raw_data": [load_raw_data, "rawDataOperations"],
  "resolve_slugs": [load_chunks, "chunksOperations"],
  "get_chunks": [load_chunks, "chunksOperations"],
  "log_ingest": [load_ingest_log, "ingestLogOperations"],
  "get_ingest_log": [load_ingest_log, "ingestLogOperations"],
  "get_usage": [load_usage, "usageOperations"],
  "file_list": [load_files, "filesOperations"],
  "file_upload": [load_files, "filesOperations"],
  "file_url": [load_files, "filesOperations"],
  "submit_job": [load_jobs, "jobsOperations"],
  "get_job": [load_jobs, "jobsOperations"],
  "list_jobs": [load_jobs, "jobsOperations"],
  "cancel_job": [load_jobs, "jobsOperations"],
  "retry_job": [load_jobs, "jobsOperations"],
  "get_job_progress": [load_jobs, "jobsOperations"],
  "pause_job": [load_jobs, "jobsOperations"],
  "resume_job": [load_jobs, "jobsOperations"],
  "replay_job": [load_jobs, "jobsOperations"],
  "send_job_message": [load_jobs, "jobsOperations"],
  "submit_agent": [load_jobs, "jobsOperations"],
  "get_agent_job": [load_jobs, "jobsOperations"],
  "get_job_stats": [load_jobs, "jobsOperations"],
  "find_orphans": [load_orphans, "orphansOperations"],
  "get_calibration_profile": [load_calibration, "calibrationOperations"],
  "takes_list": [load_takes, "takesOperations"],
  "takes_search": [load_takes, "takesOperations"],
  "think": [load_takes, "takesOperations"],
  "takes_scorecard": [load_takes, "takesOperations"],
  "takes_calibration": [load_takes, "takesOperations"],
  "takes_add": [load_takes, "takesOperations"],
  "takes_update": [load_takes, "takesOperations"],
  "takes_resolve": [load_takes, "takesOperations"],
  "takes_supersede": [load_takes, "takesOperations"],
  "takes_remove": [load_takes, "takesOperations"],
  "takes_rebuild": [load_takes, "takesOperations"],
  "whoami": [load_sources, "sourcesOperations"],
  "sources_add": [load_sources, "sourcesOperations"],
  "sources_list": [load_sources, "sourcesOperations"],
  "sources_remove": [load_sources, "sourcesOperations"],
  "sources_status": [load_sources, "sourcesOperations"],
  "sources_inspect": [load_sources, "sourcesOperations"],
  "request_tools": [load_request_tools, "requestToolsOperations"],
  "get_recent_salience": [load_salience, "salienceOperations"],
  "find_anomalies": [load_salience, "salienceOperations"],
  "get_recent_transcripts": [load_transcripts, "transcriptsOperations"],
  "connectors_status": [load_connectors, "connectorsOperations"],
  "connector_sync": [load_connectors, "connectorsOperations"],
  "chronicle_day": [load_chronicle, "chronicleOperations"],
  "chronicle_on_this_day": [load_chronicle, "chronicleOperations"],
  "chronicle_since": [load_chronicle, "chronicleOperations"],
  "chronicle_last_seen": [load_chronicle, "chronicleOperations"],
  "ontology_get": [load_chronicle, "chronicleOperations"],
  "ontology_propose": [load_chronicle, "chronicleOperations"],
  "ontology_dimensions": [load_chronicle, "chronicleOperations"],
  "ontology_conflicts": [load_chronicle, "chronicleOperations"],
  "volunteer_chronicle": [load_chronicle, "chronicleOperations"],
  "chronicle_backfill": [load_chronicle, "chronicleOperations"],
  "volunteer_context": [load_insights, "volunteer_context"],
  "extract_entities": [load_extraction, "extractionOperations"],
  "extraction_pending": [load_extraction, "extractionOperations"],
  "extraction_review": [load_extraction, "extractionOperations"],
  "entity_identity_link": [load_entity_identity, "entityIdentityOperations"],
  "entity_identity_unlink": [load_entity_identity, "entityIdentityOperations"],
  "entity_identity_list": [load_entity_identity, "entityIdentityOperations"],
  "extract_facts": [load_facts, "factsOperations"],
  "recall": [load_facts, "factsOperations"],
  "context_pack": [load_facts, "factsOperations"],
  "delta": [load_facts, "factsOperations"],
  "forget_fact": [load_facts, "factsOperations"],
  "purge_fact": [load_purge, "purgeOperations"],
  "list_page_purges": [load_purge, "purgeOperations"],
  "unpurge_page": [load_purge, "purgeOperations"],
  "find_contradictions": [load_insights, "find_contradictions"],
  "find_experts": [load_insights, "find_experts"],
  "find_trajectory": [load_insights, "find_trajectory"],
  "code_callers": [load_code_intel, "codeIntelOperations"],
  "code_callees": [load_code_intel, "codeIntelOperations"],
  "code_def": [load_code_intel, "codeIntelOperations"],
  "code_refs": [load_code_intel, "codeIntelOperations"],
  "code_blast": [load_code_intel, "codeIntelOperations"],
  "code_flow": [load_code_intel, "codeIntelOperations"],
  "code_traversal_cache_clear": [load_code_intel, "codeIntelOperations"],
  "migrate_embeddings": [load_embedding_migration, "embeddingMigrationOperations"],
  "get_active_schema_pack": [load_schema_packs, "schemaPacksOperations"],
  "list_schema_packs": [load_schema_packs, "schemaPacksOperations"],
  "schema_stats": [load_schema_packs, "schemaPacksOperations"],
  "schema_lint": [load_schema_packs, "schemaPacksOperations"],
  "schema_graph": [load_schema_packs, "schemaPacksOperations"],
  "schema_explain_type": [load_schema_packs, "schemaPacksOperations"],
  "schema_review_orphans": [load_schema_packs, "schemaPacksOperations"],
  "schema_apply_mutations": [load_schema_packs, "schemaPacksOperations"],
  "reload_schema_pack": [load_schema_packs, "schemaPacksOperations"],
  "run_onboard": [load_skillopt, "skilloptOperations"],
  "run_skillopt": [load_skillopt, "skilloptOperations"],
  "open_loops": [load_loops, "loopsOperations"],
  "loops_close": [load_loops, "loopsOperations"],
  "loops_mute": [load_loops, "loopsOperations"],
  "loops_unmute": [load_loops, "loopsOperations"],
  "mute_notice": [load_notices, "noticesOperations"],
};
