/** Embed the native provider and the canonical agent skillpack in compiled CLIs.
 * Run with Bun or Node (type stripping); --check never changes the tree. */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const assets: Record<string, string> = {};
const provider = join(root, 'integrations/hermes');
for (const name of readdirSync(provider).sort()) {
  if (name.endsWith('.py') || name === 'plugin.yaml') assets[name] = readFileSync(join(provider, name), 'utf8');
}
const skills = join(root, 'plugin/skills');
function collect(directory: string): void {
  for (const entry of readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) collect(path);
    else if (entry.isFile()) assets[`skills/${relative(skills, path).split('\\').join('/')}`] = readFileSync(path, 'utf8');
    else throw new Error(`Unsupported skill asset: ${path}`);
  }
}
collect(skills);
const output = '// Generated by scripts/generate-hermes-assets.ts. Do not edit.\n'
  + 'export const HERMES_PLUGIN_ASSETS: Readonly<Record<string, string>> = '
  + JSON.stringify(assets, null, 2) + ';\n';
const target = join(root, 'src/core/harness/hermes-assets.generated.ts');
if (process.argv.includes('--check')) {
  if (!existsSync(target) || readFileSync(target, 'utf8') !== output) {
    throw new Error('Hermes assets are stale. Run bun scripts/generate-hermes-assets.ts');
  }
} else writeFileSync(target, output);
